### ISSUE TITLE
Regarding http://nilock.github.io/MathSnips/MultQuiz/MultQuiz.html

### ISSUE THREAD

**Issue by attenboro** [NiloCK/MathSnips#1]
Hi, regarding stackexchange discussion, I see it's now possible to submit answers to numbers above 10. However, it seems when I choose smallest digit 10 and largets 20, only questions with 10_X shows up, iow all questions contain 10, there is never 13_19 or similar. Also, I can't choose to have a higher smallest digit than 10 (not a big issue).

Thanks a lot for all your work and sorry if I'm posting this wrong, I'm new to github

**Comment by NiloCK** [comment]
Will look into these between now and Sunday, I expect.

Thanks for posting here. I too am relatively new with github, so getting your feedback here helps me to learn the tooling around the local workflow.

You are posting correctly, with the small exception that the standard format for issue reporting in software is to specify as precisely as possible one malfunction or prospective feature per issue. In this case, there might have been one issue for the '10 is in every question' bug, and another for the limitation on the highest smallest digit.

**Comment by NiloCK** [comment]
The issue of no questions being generated with both multiplicands greater than ten was a side effect of the default 'MaxMin' value. I've altered the configuration page so that adjusting the Maximum also pushes up the MaxMin when that's appropriate.

Min numbers greater than ten are now permitted.
